---
# output: github_document
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-ms.tex
    number_sections: true
title: | 
        | Patrones de Asociación y Diversidad Descritos por la Familia Fabaceae Mimosoideae en  una Isla Subtropical, Cuenca del Mar Caribe.
        | *Patterns of Association and Diversity Described by the Family Fabaceae Mimosoideae on a Subtropical Island, Caribbean Sea Basin*.
        | 
author:
- name: "Welifer Junior Lebron Vicente"
  affiliation: "Estudiante de Ciencias Geográficas, Universidad Autónoma de Santo Domingo (UASD)"
abstract: "Mi resumen"
keywords: "palabra clave 1, palabra clave 2"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: bibliography.bib
# csl: plos-one.csl
csl: apa.csl
header-includes:
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
---

# Introducción

El análisis de biodiversidad forestal viabiliza la obtención de información sobre el comportamiento de las especies en su hábitat, los efectos de cambios geoestacionarios, y las probables consecuencias de actividades antrópicas en el ciclo vital de los bosques. La función de los bosques tropicales puede ser productiva (madera, fibra, leña, productos no maderables); ambientales (regulación del clima, reserva de biodiversidad, conservación de suelos y agua, etc.); y social (subsitencia de poblamientos humanos locales y su cultura) [cita1, TF Book].

La isla Barro Colorado, de coordenadas [9º 9' 0'' N, 79º 51' 0'' W], es una plataforma basáltica miocénica sobre la que descansa un bosque tropical primario compuesto por 305 especies arboreas  [cita2,C. article]. En el período 1981-2015 fue el emplazamiento de ocho censos forestales realizados por el Smithsonian Tropical Research Institute, donde la subfamilia *Fabaceae Mimosoideae* representa el 5.9% de las especies registradas en la parcela de 50 hectareas delimitada en 1980 [Cita3,WebP]. 

La familia *Mimosoideae* fue incorporada a las *Caesalpinoideae* dentro del clado mimosoide, esta subfamilia de las fabaceas es sumamente variable; compuesta principalmente por árboles y arbustos de flores asimétricas cigomorfas. El clado filogenético mimosoide es propio de climas tropicales y subtropicales, sus flores son simétricas con petalos valvados y sus especimenes tienen un gran número de estambres prominentes.    \ldots.

# Metodología

Se seleccionó la subfamilia *Fabaceae Mimosoideae* dentro del total de 59 familias censadas por el Smithsonian Tropical Research Institute en una parcela de 50 hectareas en la isla Barro Colorado. \ldots

# Resultados

\ldots

# Discusión

# Agradecimientos

# Información de soporte

\ldots

# *Script* reproducible

\ldots

# Referencias
